### PR TITLE
forgot to actually send Arch to update server

### PR DESCRIPTION
**Pull request by zanderz**
Does anything else need to happen on the server side?
@maxtaco @jzila

### CODE REVIEW

**Comment by maxtaco** [comment]
Ask @cjb and @oconnor663

**Comment by oconnor663** [comment]
(Linux doesn't go anywhere near this code, so I'm out of the loop.)

**Comment by maxtaco** [comment]
@oconnor663  -- I meant the server-side code in web/pkg.iced, weren't you there recently?

**Comment by zanderz** [comment]
It seems like the server accepts it as an optional parameter already: https://github.com/keybase/keybase/blob/master/web/pkg.iced#L59

**Comment by oconnor663** [comment]
Not since 2016 :p

**Comment by zanderz** [comment]
so, guys, where does that leave us @oconnor663 @maxtaco ?

**Pull request merged**
