### PR TITLE
Increase timeout when getting Keybase version

### PR DESCRIPTION
**Pull request by zanderz**
and use 10 second timeout instead of 5 - getting the version has failed on Windows before.
@maxtaco @gabriel

### CODE REVIEW

**Comment by gabriel** [comment]
I think this is ok..

So you're saying a user had a current version of keybase but it was timing out or erroring on the version command? Was the computer being slow or was it something else, just curious.

We could also bump up the timeout to 30s instead of retrying if it was only a timeout issue.

**Comment by gabriel** [comment]
Feel free to bump version

**Comment by zanderz** [comment]
Hard to say, here are logs: https://github.com/keybase/keybase-issues/issues/2695
I also have a speculative service PR to match: https://github.com/keybase/client/pull/5202

**Comment by gabriel** [comment]
Ah ok, if it's a keybase causing computer to run slow... can we bump up the timeout to like 20 or 30 seconds and not do retries?

Also I posted a comment in the other PR.... It appears that any `keybase` CLI command is triggering identifies to occur and not necessarily on an hourly basis.

**Pull request merged**
