### PR TITLE
Apply autoOverride to prompt also, not just installer launch

### PR DESCRIPTION
**Pull request by zanderz**
This is why we test.
@gabriel @maxtaco

### CODE REVIEW

**Comment by maxtaco** [comment]
what's `autoOverride`?

**Comment by zanderz** [comment]
Override the auto update settings, because drivers. IOW, we can't silently update if new drivers are incoming, so show the updater prompt instead of launching an installer once per hour.

**Comment by zanderz** [comment]
PS: I have tested an upgrade scenario with installers built with this

**Comment by maxtaco** [comment]
So autoOveride is specified by the server and disables auto installs?

**Comment by zanderz** [comment]
It is calculated by the client from the new driver product code props in the installer json: if they match (same driver installed as in the update), it can be silent. Before this change, autoOverride only controlled whether the installer was launched, which wasn't what I intended.

**Comment by maxtaco** [comment]
Ok, and it is only one for Windows?

If so, good to merge!

**Comment by zanderz** [comment]
The part that turns it on is windows only, yeah.

**Pull request merged**
