### PR TITLE
Add a pid file when running as a service

### PR DESCRIPTION
**Pull request by patrickxb**
This creates an updater.pid file in the CacheDir.

### CODE REVIEW

**Comment by patrickxb** [comment]
I think I fixed all the cross-platform issues...

**Comment by patrickxb** [comment]
(my launchd fallback depends on this change, so I'd like to get this in first)

**Comment by maxtaco** [comment]
Should anything else go into the CacheDir?

**Comment by maxtaco** [comment]
(ignore my comment)

**Pull request merged**
