### PR TITLE
Update deletes previous downloads

### PR DESCRIPTION
**Pull request by mlsteele**

### CODE REVIEW

**Comment by maxtaco** [comment]
LGTM for macOS. @zanderz does this do the right thing on windows?

**Comment by mlsteele** [comment]
Alright so @zanderz is this good to merge? Also this should be smoke tested. Is that part of the normal release process now?

**Comment by zanderz** [comment]
yes, a release is always smoketested. I can run the build for you first if u don't have windows.

**Comment by mlsteele** [comment]
That would be great

**Pull request merged**
